// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// DO NOT EDIT, see link below for more information:
// https://github.com/google/magika/tree/main/rust/gen

use std::borrow::Cow;

use crate::config::ModelConfig;
use crate::ContentType;

pub(crate) const CONFIG: ModelConfig = ModelConfig {
    beg_size: 512,
    mid_size: 512,
    end_size: 512,
    use_inputs_at_offsets: false,
    min_file_size_for_dl: 8,
    padding_token: 256,
    block_size: 1000,
    thresholds: Cow::Borrowed(&THRESHOLDS),
    overwrite_map: Cow::Borrowed(&OVERWRITE_MAP),
};

#[rustfmt::skip]
const THRESHOLDS: [f32; ContentType::SIZE] = [0.5, 0.5, 0.95, 0.5, 0.5, 0.5, 0.95, 0.85, 0.5, 0.5, 0.5, 0.5, 0.65, 0.5, 0.5, 0.95, 0.95, 0.7, 0.95, 0.95, 0.95, 0.5, 0.5, 0.5, 0.95, 0.5, 0.5, 0.5, 0.95, 0.95, 0.5, 0.5, 0.5, 0.5, 0.95, 0.95, 0.5, 0.5, 0.5, 0.95, 0.5, 0.5, 0.91, 0.5, 0.5, 0.5, 0.95, 0.5, 0.95, 0.95, 0.5, 0.95, 0.5, 0.5, 0.95, 0.5, 0.5, 0.5, 0.5, 0.95, 0.5, 0.5, 0.95, 0.5, 0.5, 0.95, 0.5, 0.5, 0.5, 0.5, 0.95, 0.5, 0.75, 0.5, 0.95, 0.5, 0.5, 0.55, 0.95, 0.5, 0.95, 0.55, 0.91, 0.95, 0.8, 0.5, 0.5, 0.95, 0.75, 0.5, 0.5, 0.5, 0.5, 0.5, 0.95, 0.95, 0.5, 0.95, 0.5, 0.95, 0.95, 0.9, 0.5, 0.95, 0.5, 0.5, 0.95, 0.95, 0.95, 0.7, 0.95, 0.5, 0.5, 0.5, 0.5, 0.5, 0.95, 0.95, 0.95, 0.95, 0.95, 0.5, 0.5, 0.5, 0.95, 0.5, 0.5, 0.95, 0.5, 0.95, 0.95, 0.95, 0.85, 0.5, 0.5, 0.95, 0.5, 0.95, 0.95, 0.7, 0.85, 0.5, 0.5, 0.5, 0.5, 0.85, 0.95, 0.5, 0.5, 0.95, 0.95, 0.95, 0.95, 0.95, 0.93, 0.95, 0.95, 0.5, 0.95, 0.5, 0.85, 0.95, 0.5, 0.5, 0.7, 0.5, 0.95, 0.5, 0.5, 0.5, 0.5, 0.95, 0.95, 0.5, 0.95, 0.95, 0.5, 0.5, 0.95, 0.5, 0.95, 0.5, 0.95, 0.5, 0.95, 0.5, 0.94, 0.5, 0.5, 0.95, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.95, 0.95, 0.95, 0.95, 0.95, 0.5, 0.5, 0.95, 0.75, 0.5, 0.95, 0.7, 0.93, 0.95, 0.7, 0.5, 0.5, 0.95, 0.95];
const OVERWRITE_MAP: [ContentType; ContentType::SIZE] = [
    ContentType::_3gp,
    ContentType::Ace,
    ContentType::Ai,
    ContentType::Aidl,
    ContentType::Apk,
    ContentType::Applebplist,
    ContentType::Appleplist,
    ContentType::Asm,
    ContentType::Asp,
    ContentType::Autohotkey,
    ContentType::Autoit,
    ContentType::Awk,
    ContentType::Batch,
    ContentType::Bazel,
    ContentType::Bib,
    ContentType::Bmp,
    ContentType::Bzip,
    ContentType::C,
    ContentType::Cab,
    ContentType::Cat,
    ContentType::Chm,
    ContentType::Clojure,
    ContentType::Cmake,
    ContentType::Cobol,
    ContentType::Coff,
    ContentType::Coffeescript,
    ContentType::Cpp,
    ContentType::Crt,
    ContentType::Crx,
    ContentType::Cs,
    ContentType::Csproj,
    ContentType::Css,
    ContentType::Csv,
    ContentType::Dart,
    ContentType::Deb,
    ContentType::Dex,
    ContentType::Dicom,
    ContentType::Diff,
    ContentType::Dm,
    ContentType::Dmg,
    ContentType::Doc,
    ContentType::Dockerfile,
    ContentType::Docx,
    ContentType::Dsstore,
    ContentType::Dwg,
    ContentType::Dxf,
    ContentType::Elf,
    ContentType::Elixir,
    ContentType::Emf,
    ContentType::Eml,
    ContentType::Empty,
    ContentType::Epub,
    ContentType::Erb,
    ContentType::Erlang,
    ContentType::Flac,
    ContentType::Flv,
    ContentType::Fortran,
    ContentType::Gemfile,
    ContentType::Gemspec,
    ContentType::Gif,
    ContentType::Gitattributes,
    ContentType::Gitmodules,
    ContentType::Go,
    ContentType::Gradle,
    ContentType::Groovy,
    ContentType::Gzip,
    ContentType::H5,
    ContentType::Handlebars,
    ContentType::Haskell,
    ContentType::Hcl,
    ContentType::Hlp,
    ContentType::Htaccess,
    ContentType::Html,
    ContentType::Icns,
    ContentType::Ico,
    ContentType::Ics,
    ContentType::Ignorefile,
    ContentType::Ini,
    ContentType::Internetshortcut,
    ContentType::Ipynb,
    ContentType::Iso,
    ContentType::Jar,
    ContentType::Java,
    ContentType::Javabytecode,
    ContentType::Javascript,
    ContentType::Jinja,
    ContentType::Jp2,
    ContentType::Jpeg,
    ContentType::Json,
    ContentType::Jsonl,
    ContentType::Julia,
    ContentType::Kotlin,
    ContentType::Latex,
    ContentType::Lha,
    ContentType::Lisp,
    ContentType::Lnk,
    ContentType::Lua,
    ContentType::M3u,
    ContentType::M4,
    ContentType::Macho,
    ContentType::Makefile,
    ContentType::Markdown,
    ContentType::Matlab,
    ContentType::Mht,
    ContentType::Midi,
    ContentType::Mkv,
    ContentType::Mp3,
    ContentType::Mp4,
    ContentType::Mscompress,
    ContentType::Msi,
    ContentType::Mum,
    ContentType::Npy,
    ContentType::Npz,
    ContentType::Nupkg,
    ContentType::Objectivec,
    ContentType::Ocaml,
    ContentType::Odex,
    ContentType::Odp,
    ContentType::Ods,
    ContentType::Odt,
    ContentType::Ogg,
    ContentType::One,
    ContentType::Onnx,
    ContentType::Otf,
    ContentType::Outlook,
    ContentType::Parquet,
    ContentType::Pascal,
    ContentType::Pcap,
    ContentType::Pdb,
    ContentType::Pdf,
    ContentType::Pebin,
    ContentType::Pem,
    ContentType::Perl,
    ContentType::Php,
    ContentType::Pickle,
    ContentType::Png,
    ContentType::Po,
    ContentType::Postscript,
    ContentType::Powershell,
    ContentType::Ppt,
    ContentType::Pptx,
    ContentType::Prolog,
    ContentType::Proteindb,
    ContentType::Proto,
    ContentType::Psd,
    ContentType::Python,
    ContentType::Pythonbytecode,
    ContentType::Qt,
    ContentType::R,
    ContentType::Rar,
    ContentType::Rdf,
    ContentType::Rpm,
    ContentType::Rst,
    ContentType::Rtf,
    ContentType::Ruby,
    ContentType::Rust,
    ContentType::Scala,
    ContentType::Scss,
    ContentType::Sevenzip,
    ContentType::Sgml,
    ContentType::Shell,
    ContentType::Smali,
    ContentType::Snap,
    ContentType::Solidity,
    ContentType::Sql,
    ContentType::Sqlite,
    ContentType::Squashfs,
    ContentType::Srt,
    ContentType::Stlbinary,
    ContentType::Stltext,
    ContentType::Sum,
    ContentType::Svg,
    ContentType::Swf,
    ContentType::Swift,
    ContentType::Symlinktext,
    ContentType::Tar,
    ContentType::Tcl,
    ContentType::Textproto,
    ContentType::Tga,
    ContentType::Thumbsdb,
    ContentType::Tiff,
    ContentType::Toml,
    ContentType::Torrent,
    ContentType::Tsv,
    ContentType::Ttf,
    ContentType::Twig,
    ContentType::Txt,
    ContentType::Typescript,
    ContentType::Undefined,
    ContentType::Unknown,
    ContentType::Vba,
    ContentType::Vcxproj,
    ContentType::Verilog,
    ContentType::Vhdl,
    ContentType::Vtt,
    ContentType::Vue,
    ContentType::Wasm,
    ContentType::Wav,
    ContentType::Webm,
    ContentType::Webp,
    ContentType::Winregistry,
    ContentType::Wmf,
    ContentType::Woff,
    ContentType::Woff2,
    ContentType::Xar,
    ContentType::Xls,
    ContentType::Xlsb,
    ContentType::Xlsx,
    ContentType::Xml,
    ContentType::Xpi,
    ContentType::Xz,
    ContentType::Yaml,
    ContentType::Yara,
    ContentType::Zig,
    ContentType::Zip,
    ContentType::Zlibstream,
];

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
#[allow(dead_code)] // only constructed through transmute
pub(crate) enum Label {
    Ai,
    Apk,
    Appleplist,
    Asm,
    Asp,
    Batch,
    Bmp,
    Bzip,
    C,
    Cab,
    Cat,
    Chm,
    Coff,
    Crx,
    Cs,
    Css,
    Csv,
    Deb,
    Dex,
    Dmg,
    Doc,
    Docx,
    Elf,
    Emf,
    Eml,
    Epub,
    Flac,
    Gif,
    Go,
    Gzip,
    Hlp,
    Html,
    Ico,
    Ini,
    Internetshortcut,
    Iso,
    Jar,
    Java,
    Javabytecode,
    Javascript,
    Jpeg,
    Json,
    Latex,
    Lisp,
    Lnk,
    M3u,
    Macho,
    Makefile,
    Markdown,
    Mht,
    Mp3,
    Mp4,
    Mscompress,
    Msi,
    Mum,
    Odex,
    Odp,
    Ods,
    Odt,
    Ogg,
    Outlook,
    Pcap,
    Pdf,
    Pebin,
    Pem,
    Perl,
    Php,
    Png,
    Postscript,
    Powershell,
    Ppt,
    Pptx,
    Python,
    Pythonbytecode,
    Rar,
    Rdf,
    Rpm,
    Rst,
    Rtf,
    Ruby,
    Rust,
    Scala,
    Sevenzip,
    Shell,
    Smali,
    Sql,
    Squashfs,
    Svg,
    Swf,
    Symlinktext,
    Tar,
    Tga,
    Tiff,
    Torrent,
    Ttf,
    Txt,
    Unknown,
    Vba,
    Wav,
    Webm,
    Webp,
    Winregistry,
    Wmf,
    Xar,
    Xls,
    Xlsb,
    Xlsx,
    Xml,
    Xpi,
    Xz,
    Yaml,
    Zip,
    Zlibstream,
}

pub(crate) const NUM_LABELS: usize = 113;
impl Label {
    pub(crate) fn content_type(self) -> ContentType {
        match self {
            Label::Ai => ContentType::Ai,
            Label::Apk => ContentType::Apk,
            Label::Appleplist => ContentType::Appleplist,
            Label::Asm => ContentType::Asm,
            Label::Asp => ContentType::Asp,
            Label::Batch => ContentType::Batch,
            Label::Bmp => ContentType::Bmp,
            Label::Bzip => ContentType::Bzip,
            Label::C => ContentType::C,
            Label::Cab => ContentType::Cab,
            Label::Cat => ContentType::Cat,
            Label::Chm => ContentType::Chm,
            Label::Coff => ContentType::Coff,
            Label::Crx => ContentType::Crx,
            Label::Cs => ContentType::Cs,
            Label::Css => ContentType::Css,
            Label::Csv => ContentType::Csv,
            Label::Deb => ContentType::Deb,
            Label::Dex => ContentType::Dex,
            Label::Dmg => ContentType::Dmg,
            Label::Doc => ContentType::Doc,
            Label::Docx => ContentType::Docx,
            Label::Elf => ContentType::Elf,
            Label::Emf => ContentType::Emf,
            Label::Eml => ContentType::Eml,
            Label::Epub => ContentType::Epub,
            Label::Flac => ContentType::Flac,
            Label::Gif => ContentType::Gif,
            Label::Go => ContentType::Go,
            Label::Gzip => ContentType::Gzip,
            Label::Hlp => ContentType::Hlp,
            Label::Html => ContentType::Html,
            Label::Ico => ContentType::Ico,
            Label::Ini => ContentType::Ini,
            Label::Internetshortcut => ContentType::Internetshortcut,
            Label::Iso => ContentType::Iso,
            Label::Jar => ContentType::Jar,
            Label::Java => ContentType::Java,
            Label::Javabytecode => ContentType::Javabytecode,
            Label::Javascript => ContentType::Javascript,
            Label::Jpeg => ContentType::Jpeg,
            Label::Json => ContentType::Json,
            Label::Latex => ContentType::Latex,
            Label::Lisp => ContentType::Lisp,
            Label::Lnk => ContentType::Lnk,
            Label::M3u => ContentType::M3u,
            Label::Macho => ContentType::Macho,
            Label::Makefile => ContentType::Makefile,
            Label::Markdown => ContentType::Markdown,
            Label::Mht => ContentType::Mht,
            Label::Mp3 => ContentType::Mp3,
            Label::Mp4 => ContentType::Mp4,
            Label::Mscompress => ContentType::Mscompress,
            Label::Msi => ContentType::Msi,
            Label::Mum => ContentType::Mum,
            Label::Odex => ContentType::Odex,
            Label::Odp => ContentType::Odp,
            Label::Ods => ContentType::Ods,
            Label::Odt => ContentType::Odt,
            Label::Ogg => ContentType::Ogg,
            Label::Outlook => ContentType::Outlook,
            Label::Pcap => ContentType::Pcap,
            Label::Pdf => ContentType::Pdf,
            Label::Pebin => ContentType::Pebin,
            Label::Pem => ContentType::Pem,
            Label::Perl => ContentType::Perl,
            Label::Php => ContentType::Php,
            Label::Png => ContentType::Png,
            Label::Postscript => ContentType::Postscript,
            Label::Powershell => ContentType::Powershell,
            Label::Ppt => ContentType::Ppt,
            Label::Pptx => ContentType::Pptx,
            Label::Python => ContentType::Python,
            Label::Pythonbytecode => ContentType::Pythonbytecode,
            Label::Rar => ContentType::Rar,
            Label::Rdf => ContentType::Rdf,
            Label::Rpm => ContentType::Rpm,
            Label::Rst => ContentType::Rst,
            Label::Rtf => ContentType::Rtf,
            Label::Ruby => ContentType::Ruby,
            Label::Rust => ContentType::Rust,
            Label::Scala => ContentType::Scala,
            Label::Sevenzip => ContentType::Sevenzip,
            Label::Shell => ContentType::Shell,
            Label::Smali => ContentType::Smali,
            Label::Sql => ContentType::Sql,
            Label::Squashfs => ContentType::Squashfs,
            Label::Svg => ContentType::Svg,
            Label::Swf => ContentType::Swf,
            Label::Symlinktext => ContentType::Symlinktext,
            Label::Tar => ContentType::Tar,
            Label::Tga => ContentType::Tga,
            Label::Tiff => ContentType::Tiff,
            Label::Torrent => ContentType::Torrent,
            Label::Ttf => ContentType::Ttf,
            Label::Txt => ContentType::Txt,
            Label::Unknown => ContentType::Unknown,
            Label::Vba => ContentType::Vba,
            Label::Wav => ContentType::Wav,
            Label::Webm => ContentType::Webm,
            Label::Webp => ContentType::Webp,
            Label::Winregistry => ContentType::Winregistry,
            Label::Wmf => ContentType::Wmf,
            Label::Xar => ContentType::Xar,
            Label::Xls => ContentType::Xls,
            Label::Xlsb => ContentType::Xlsb,
            Label::Xlsx => ContentType::Xlsx,
            Label::Xml => ContentType::Xml,
            Label::Xpi => ContentType::Xpi,
            Label::Xz => ContentType::Xz,
            Label::Yaml => ContentType::Yaml,
            Label::Zip => ContentType::Zip,
            Label::Zlibstream => ContentType::Zlibstream,
        }
    }
}
